### ISSUE TITLE
Explain how to convert a pytorch model to IREE.gd

### ISSUE THREAD

**Issue by fire** [iree-gd/iree.gd#65]
### Describe the proposed feature and its relevance to inferencing

Document how to take a random PyTorch model and make it run in Godot Engine IREE.gd

### Context or use case

1. https://github.com/collabora/WhisperSpeech

Write instructions how to convert a random PyTorch model and inference end to end.

### Proposed solution

Instructions are written

### Additional information

Seems hard.

**Comment by fire** [comment]
@aiaimimi0920 might be interested

**Comment by aiaimimi0920** [comment]
It seems that iree provides a compiler API : https://iree.dev/reference/bindings/c-api/#compiler-api

it a sample : https://github.com/openxla/iree/blob/main/integrations/pjrt/src/iree_pjrt/common/iree_compiler.cc

Based on your question: https://github.com/RechieKho/iree.gd/issues/35 
Do you want players to use models such as pytouch for AI inference at runtime?

Finally, what help do you want me to do?

**Comment by fire** [comment]
I want to know if you would use this.

Text to speech.

[tts_unified_expressions_06.zip](https://github.com/RechieKho/iree.gd/files/14015385/tts_unified_expressions_06.zip)

WhipserSpeech should support other languages than English.

**Comment by fire** [comment]
The idea is for a game npc to speak using the TTS and understand input via godot_whisper. I am not sure if regular devices have enough performance to handle text models

**Comment by aiaimimi0920** [comment]
Currently, for my [mimi pet:](https://github.com/aiaimimi0920/mimi)  I always need to use a C++alternative version of the AI model to achieve my goals, because I want it to run in Godot and cross platform

such as

1. [llama.cpp](https://github.com/ggerganov/llama.cpp) replaces llama:
2. [Whisper.cpp](https://github.com/ggerganov/whisper.cpp) replaces Whisper: [godot Whisper](https://github.com/V-Sekai/godot-whisper)
3. [SummerTTS](https://github.com/huakunyang/SummerTTS) replace tts: [godot tts](https://github.com/aiaimimi0920/godot-tts)

If iree.gd can run the pytouch model seamlessly on most devices without significant performance loss, then it will become my preferred solution to run ai model in godot.

If you are asking me if I am interested in using WhisperSpeech as tts in Godot, I am indeed interested, but it will not be my high priority because I have implemented a Godot tts plugin based on summerts, which can support Chinese, English, and Japanese.

**Comment by RechieKho** [comment]
Hello, thank you for taking interest in IREE.gd! I haven't try out pytorch models but there is [documentation](https://iree.dev/guides/ml-frameworks/pytorch/) on IREE's official website on how to preprocess them. Once you get the `.vmfb` bytecode then it would be the same as shown in the sample.

For the development part, there is still 2 problem to deal with before using it in games:

- asynchronous execution. So currently there is only synchronous execution, which blocking the main thread and making Godot freeze. It would brings a better UX if it doesn't freeze.

- Release to Apple platform. As mentioned in the readme, there is some technical issue on that. But quite recently, like 7 hours ago, I have been notified that it might be resolved. I'll deal with that later on.

**Comment by aiaimimi0920** [comment]
asynchronous execution ： you can use godot thread, like [this ](https://github.com/aiaimimi0920/godot-tts/blob/main/src/text_to_speech.cpp):
```
this->infer_thread = memnew(Thread);
this->infer_thread->start(callable_mp(this, &TTSSpeaker::process_message_infer), Thread::Priority::PRIORITY_NORMAL);

bool TTSSpeaker::process_message_infer() {
......
TextToSpeech::get_singleton()->call_deferred("emit_signal", "generated_audio_buffer", p_data,);
}
```

**Comment by RechieKho** [comment]
I tried to implement that for the past 5 hours. Godot goes weird and crazy, shutdown without any error. I speculate it is because of the rapid issuing of threads (?), or maybe I must use IREE way of spawning threads.

I realised that sometime, you need to run the ML model multiple times before getting the result, such as the sample which requires the image to be spliced into 50x50 resolution and process all the images. Instead of creating a thread for each execution, maybe it is up to the user to decide when to start the thread in gdscript (https://docs.godotengine.org/en/stable/tutorials/performance/using_multiple_threads.html#threads). 

I'm not sure about parallel execution for ML model though, not sure how much it will benefit us.

**Comment by aiaimimi0920** [comment]
Perhaps I can help you?

Does the code you have completed have a branch?
@RechieKho

**Comment by RechieKho** [comment]
https://github.com/RechieKho/iree.gd/assets/50512341/5c0bd4e1-e62a-42c4-9136-097759343f85

I think what I need is a good night sleep. Asynchronous execution attained!

**Comment by GeorgeS2019** [comment]
https://iree.dev/guides/ml-frameworks/pytorch/#ahead-of-time-aot-export
![image](https://github.com/user-attachments/assets/822b7984-371b-4a14-a834-01cd41163478)

**Comment by RechieKho** [comment]
I hope someone could make a PyTorch example in IREE.gd.

**Comment by fire** [comment]
It might be helpful to figure out how to run https://huggingface.co/microsoft/Phi-3.5-mini-instruct. It's one of the stronger smaller large language models.

**Comment by GeorgeS2019** [comment]
The challenge for IREE for godot is the lack of maturity of IREE as a whole. 

It is easy to claim compatibility with pytorch, etc. Until there is sufficient uptake by the AI community to test the so claim compatibility, it remains high risk to adopt IREE when there are many more established tested options for Godot to access all these LLM models through e.g. c# for Phi3.5

**Comment by fire** [comment]
> The challenge for IREE for godot is the lack of maturity of IREE as a whole.
>
> It is easy to claim compatibility with pytorch, etc. Until there is sufficient uptake by the AI community to test the so claim compatibility, it remains high risk to adopt IREE when there are many more established tested options for Godot to access all these LLM models through e.g. c# for Phi3.5

Perfect compatibility can already be achieved with Godot Python: [Godot Python Extension](https://github.com/maiself/godot-python-extension).

However, IREE offers several advantages that make it worth considering despite its current maturity level. Firstly, IREE is designed to provide performant machine learning inference on a wide range of hardware platforms, including CPUs, GPUs, and specialized accelerators. This flexibility can lead to significant performance improvements and cost savings in the long run.

Secondly, IREE's focus on local-first execution aligns perfectly with our goal of native machine learning integration for Godot Engine. By running models locally, we can reduce latency, improve privacy, and eliminate dependency on external services, which is crucial for applications requiring real-time processing and offline capabilities.

Lastly, adopting IREE early allows us to contribute to its development and shape its future direction to better meet our needs. While this approach carries some risk, it also allows us to innovate within game engines.

**Comment by fire** [comment]
I can’t use c# so if you must use c# you need to deal with gc pauses. Also I am going yo ignore your comment because it caused our project to take a pause

**Comment by fire** [comment]
I could look into pytorch in iree any good idea for models?

**Comment by GeorgeS2019** [comment]
@fire 

There are custom c++ operators in pytorch, which are beyond just pure python,  which are likely excluded, in early stage project like IREE.  Check with the IREE developers to see if they have anticipated such challenges. These are beyond me, I read about these, when working with TorchSharp.

**Comment by fire** [comment]
Documentation added to https://iree-gd.github.io/iree.gd.docs/iree.gd/#porting-machine-learning-models
